# Generated by Django 3.1 on 2020-08-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOT', '0002_auto_20200823_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='mapped_io',
            field=models.CharField(default='a', max_length=25),
        ),
    ]
