# Generated by Django 3.1 on 2020-08-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOT', '0003_button_mapped_io'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('mapped_io', models.CharField(default='a', max_length=25)),
            ],
        ),
    ]
